# Generated by Django 2.2.7 on 2019-12-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20191203_0525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='innovation',
            old_name='average_score',
            new_name='rating',
        ),
    ]
