# Generated by Django 2.2.7 on 2019-12-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20191206_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ai',
            old_name='average_score',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='hardware_iot',
            old_name='average_score',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='intellectual_property',
            old_name='average_score',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='product_design',
            old_name='average_score',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='programming',
            old_name='average_score',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='average_score',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='software_platforms',
            old_name='average_score',
            new_name='rating',
        ),
    ]
