# Generated by Django 2.2.7 on 2019-12-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20191206_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='intellectual_property',
            name='key_word_seaching',
            field=models.IntegerField(blank=True, choices=[(10, 'LEANER'), (20, 'THINKER'), (30, 'HACKER'), (40, 'ENGINEER'), (50, 'EXPERT')], default=0, null=True),
        ),
    ]
